name: gonggoo_app
description: A Flutter marketplace app with consistent design system
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
    
  # Firebase - Xcode 16.3 호환성을 위한 최신 버전들
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_app_check: ^0.3.1+4
  cloud_functions: ^5.1.3

  # State Management - 최신 호환 버전
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Networking - 최신 호환 버전
  dio: ^5.7.0
  http: ^1.2.2
  connectivity_plus: ^6.1.4
  
  # Storage - 최신 호환 버전
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  
  # UI - 최신 호환 버전
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_markdown: ^0.7.7
  webview_flutter: ^4.4.4
  
  # TossPayments - 최신 호환 버전
  tosspayments_widget_sdk_flutter: ^2.1.1
  
  # Utility - 최신 호환 버전
  equatable: ^2.0.5
  jwt_decoder: ^2.0.1
  logger: ^2.4.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  dots_indicator: ^4.0.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  json_annotation: ^4.9.0
  web: ^1.1.1
  # geoflutterfire2: ^2.3.15  # 호환성 문제로 일시적으로 비활성화

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  custom_lint: ^0.7.5
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700 

# 주의: 토스페이먼츠는 webview_flutter_android 3.16.0 이하를 권장하지만,
# 해당 버전은 Flutter v1 embedding 이슈로 현재 Flutter 버전과 호환되지 않음
# 최신 버전 사용 후 카드앱 호출 이슈 모니터링 필요
# dependency_overrides:
#   webview_flutter_android: 3.16.0 