name: gonggoo_app
description: A Flutter marketplace app with consistent design system
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  intl: ^0.19.0
  provider: ^6.0.5
  
  # Firebase
  firebase_core: ^3.0.3
  firebase_auth: ^5.0.3
  cloud_firestore: ^5.0.3
  firebase_storage: ^12.0.0
  firebase_app_check: ^0.3.0
  
  # State Management
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Networking
  dio: ^5.3.4
  connectivity_plus: ^5.0.2
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # UI
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.1.2
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_markdown: ^0.7.7
  webview_flutter: ^4.4.2
  
  # Utility
  equatable: ^2.0.5
  jwt_decoder: ^2.0.1
  logger: ^2.0.2+1
  uuid: ^4.2.1
  geolocator: ^10.1.0
  url_launcher: ^6.2.2
  dots_indicator: ^4.0.1
  # geoflutterfire2: ^2.3.15  # 호환성 문제로 일시적으로 비활성화

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700 