// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9n8Aku3T2OCNgoJm01mE8V8vqmUz7XQw',
    appId: '1:343081223442:web:ad1ae058cbcfecdebe9fcb',
    messagingSenderId: '343081223442',
    projectId: 'si-gonggoo-app-pjh',
    authDomain: 'si-gonggoo-app-pjh.firebaseapp.com',
    storageBucket: 'si-gonggoo-app-pjh.firebasestorage.app',
    measurementId: 'G-1CJSLND6P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSZM0yNsAm85zBuZeWp-FNMIt_5iHDRXI',
    appId: '1:343081223442:android:76fc986aa044650abe9fcb',
    messagingSenderId: '343081223442',
    projectId: 'si-gonggoo-app-pjh',
    storageBucket: 'si-gonggoo-app-pjh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtHz-LRGUAN43OcXeFEWAGBmv2jXBU5R0',
    appId: '1:343081223442:ios:dcf1d2c62d550e15be9fcb',
    messagingSenderId: '343081223442',
    projectId: 'si-gonggoo-app-pjh',
    storageBucket: 'si-gonggoo-app-pjh.firebasestorage.app',
    iosBundleId: 'com.example.gonggooApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtHz-LRGUAN43OcXeFEWAGBmv2jXBU5R0',
    appId: '1:343081223442:ios:dcf1d2c62d550e15be9fcb',
    messagingSenderId: '343081223442',
    projectId: 'si-gonggoo-app-pjh',
    storageBucket: 'si-gonggoo-app-pjh.firebasestorage.app',
    iosBundleId: 'com.example.gonggooApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9n8Aku3T2OCNgoJm01mE8V8vqmUz7XQw',
    appId: '1:343081223442:web:68be9092819834b5be9fcb',
    messagingSenderId: '343081223442',
    projectId: 'si-gonggoo-app-pjh',
    authDomain: 'si-gonggoo-app-pjh.firebaseapp.com',
    storageBucket: 'si-gonggoo-app-pjh.firebasestorage.app',
    measurementId: 'G-ZE5T7X6YQ5',
  );
}
